Project.Template.Web/Areas/System/Controllers/RoleController.cs
using APP.Core.Utilities;
using Framework.Enums;
using Framework.Models.Role;
using Framework.Role;
using Service.Abstracts;
using System.ComponentModel;
using System.Web.Mvc;

namespace Project.Template.Web.Areas.System.Controllers
{
    public class RoleController : Controller
    {
        private IRoleService RoleService { get; set; }


        [Description("角色列表")]
        public ActionResult List()
        {
            return View(new SearchCondition());
        }

        [HttpPost]
        [Description("角色列表")]
        public string List(SearchCondition condition)
        {
            return JsonUtility.Serialize(RoleService.Search(condition));
        }

        [HttpPost]
        [Description("更新角色状态")]
        public string UpdateStatus(RoleCode roleCode, SysRoleStatus status)
        {
            RoleService.UpdateStatus(roleCode, status);
            return JsonUtility.SerializeAjaxSuccessJSON();
        }


        [Description("编辑角色")]
        public ActionResult Edit(RoleCode roleCode)
        {
            return View(RoleService.GetInfo(roleCode));
        }

        [HttpPost]
        [Description("保存角色信息")]
        public string Save(RoleInfo model)
        {
            var role = RoleService.SaveInfo(model);
            return JsonUtility.SerializeAjaxSuccessJSON(data: role);
        }
    }
}

Project.Template.Web/Areas/System/Views/Role/Edit.cshtml
@using Framework.Privilege
@model Framework.Models.Role.RoleInfo
@{ Layout = null; }

<div class="row">
    <div class="col-sm-20 col-sm-offset-2">
        @using (Html.BeginForm("Save", "Role", new { param = "" }, FormMethod.Post, new { @class = "form-horizontal" }))
        {
            <div class="form-group">
                @Html.RequireLabelFor(m => m.RoleCode, new { @class = "control-label" })
                @Html.PlaceholderTextBoxFor(m => m.RoleCode, new { @class = "form-control", @readonly = true })
                @Html.ValidationMessageFor(m => m.RoleCode)
            </div>

            <div class="form-group mt30">
                @Html.RequireLabelFor(m => m.Name, new { @class = "control-label" })
                @Html.PlaceholderTextBoxFor(m => m.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Name)
            </div>
            <div class="form-group">
                @Html.RequireLabelFor(m => m.Description, new { @class = "control-label" })
                @Html.PlaceholderTextBoxFor(m => m.Description, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Description)
            </div>

            <div class="form-group">
                @Html.RequireLabelFor(m => m.PrivilegeList, new { @class = "control-label require" })
                <div class="alert alert-default mb0">
                    @{
                        var privilegeList = EnumExtension.GetEnumList<PrivilegeCode>()
                            .Select(code =>
                            {
                                var group = code.ToString().Replace("URL_", null);
                                group = group.Substring(0, group.LastIndexOf("_"));
                                return new RazorExtension.InputSelectItem
                                {
                                    Text = code.ToMessage(),
                                    Value = code,
                                    IsChecked = Model.PrivilegeList.Contains(code),
                                    HtmlAttributes = new Dictionary<string, object>
                                    {
                                        { "data-title", code },
                                        { "data-group", group }
                                    }
                                };
                            })
                            .OrderBy(code => code.Value);

                        @Html.CheckBoxListFor(m => m.PrivilegeList, privilegeList, new { @class = "checkbox-inline checkbox-primary" })
                    }
                </div>
                @Html.CollectionLengthValidationMessageFor(m => m.PrivilegeList)
            </div>

            <div class="form-group mt30">
                <div class="row">
                    <div class="col-sm-12">
                        <label class="checkbox checkbox-primary">
                            @Html.CheckBoxFor(m => m.IsEnabled)
                            <span>启用角色</span>
                        </label>
                    </div>
                    <div class="col-sm-12">
                        <button type="submit" class="btn btn-primary btn-block">确定</button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Project.Template.Web/Areas/System/Views/Role/List.cshtml
@model Framework.Models.Role.SearchCondition

@section footerSection {
    @Html.HashVersionPathFor("/Areas/System/Content/Scripts/Role/list.js")
}

<div class="panel panel-white">
    <div class="panel-body">
        @using (Html.BeginForm("List", "Role", FormMethod.Post, new { @class = "form-horizontal pt10 datagrid-search" }))
        {
            <div class="form-group">
                <div class="col-sm-6">
                    @Html.PlaceholderTextBoxFor(m => m.Name, new { @class = "form-control" }, format: "搜索{0}")
                </div>

                <div class="col-sm-18 datalist-action">
                    <button class="btn btn-primary">
                        <i class="fa fa-search"></i>
                        查询
                    </button>
                </div>
            </div>
        }

        <div id="datalist"></div>
    </div>
</div>