Project.Template.Web/Areas/System/Controllers/MenuController.cs
using APP.Core.Utilities;
using Framework.Models.Menu;
using Service.Abstracts;
using System.Collections.Generic;
using System.ComponentModel;
using System.Web.Mvc;

namespace Project.Template.Web.Areas.System.Controllers
{
    public class MenuController : Controller
    {
        private IMenuService MenuService { get; set; }


        [Description("配置菜单")]
        public ActionResult Index()
        {
            ViewBag.MenuList = MenuService.GetAllMenu();

            return View();
        }

        [Description("添加父菜单")]
        public ActionResult ParentMenu()
        {
            return View(new MenuInfo());
        }

        [Description("添加子菜单")]
        public ActionResult SubMenu(bool canAddParentMenu)
        {
            ViewBag.CanAddParentMenu = canAddParentMenu;

            return View();
        }

        [Description("编辑菜单")]
        public ActionResult Edit(MenuInfo info)
        {
            return View(info);
        }


        [HttpPost]
        [Description("更新菜单")]
        public string Update(IEnumerable<MenuInfo> model)
        {
            MenuService.Update(model);

            return JsonUtility.SerializeAjaxSuccessJSON();
        }
    }
}

Project.Template.Web/Areas/System/Views/Menu/Edit.cshtml
@model Framework.Models.Menu.MenuInfo
@{ Layout = null; }

<div class="row">
    <div class="col-sm-20 col-sm-offset-2">
        @using (Html.BeginForm("Edit", "Menu", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            var codeString = Model.Privilege.ToString();

            <div class="form-group">
                @Html.RequireLabelFor(m => m.Privilege, new { @class = "control-label" })
                @Html.TextBoxFor(m => codeString, new { @class = "form-control", @readonly = true, placeholder = "未绑定界面权限" })
                @Html.ValidationMessageFor(m => m.Privilege)
            </div>

            <div class="form-group mt30">
                <div class="row">
                    <div class="col-sm-15">
                        @Html.RequireLabelFor(m => m.Name, new { @class = "control-label" })
                        @Html.PlaceholderTextBoxFor(m => m.Name, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Name)
                    </div>
                    <div class="col-sm-9">
                        @Html.RequireLabelFor(m => m.Icon, new { @class = "control-label" })
                        @Html.PlaceholderTextBoxFor(m => m.Icon, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Icon)
                    </div>
                </div>
            </div>
            <div class="form-group">
                @Html.RequireLabelFor(m => m.Description, new { @class = "control-label" })
                @Html.PlaceholderTextBoxFor(m => m.Description, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Description)
            </div>

            <div class="form-group mt30">
                <button type="submit" class="btn btn-primary btn-block">确定</button>
            </div>
        }
    </div>
</div>

Project.Template.Web/Areas/System/Views/Menu/Index.cshtml
@using Framework.Models.Menu
@{
    var menuMaxDeep = WebsiteSetting.MenuMaxDeep;
    var menuList = ViewBag.MenuList as IEnumerable<MenuInfo>;
}

@section headerSection {
    <style type="text/css">
        .dd-collapse, .dd-expand {
            display: none !important;
            font-weight: normal;
        }
    </style>
}

@section footerSection {
    <script type="text/javascript">
        var MenuMaxDeep = @(menuMaxDeep);
        @Html.ListToJson(menuList, "MenuList")
    </script>
    @Html.HashVersionPathFor("/Content/Plugins/nestable/jquery.nestable.js")
    @Html.HashVersionPathFor("/Areas/System/Content/Scripts/Menu/index.js")
}

<div class="panel panel-white">
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-12">
                <div id="menuContainer" class="dd mt-5"></div>

                <button type="button" class="btn btn-default btn-block mt30" onclick="addParentMenu(undefined, 1)">添加1级菜单</button>
                <button id="btnSave" type="button" class="btn btn-primary btn-block mt10">保存并清空缓存</button>
            </div>

            <div class="col-sm-12">
                <div class="alert alert-info">
                    <ol class="text-lh-lg ml20 mb0">
                        <li>最多允许 <strong class="text-danger">@(menuMaxDeep)级</strong> 菜单；</li>
                        <li>父级菜单不允许绑定界面（已绑定的不生效）；</li>
                        <li>修改菜单后，<strong class="text-danger">必须保存</strong> 才会生效；</li>
                    </ol>
                </div>

                <div class="alert">
                    <div>UPDATE SYS_MENU SET ParentMenuId = NULL;</div>
                    <div>DELETE FROM sys_menu;</div>
                    <div>ALTER TABLE sys_menu AUTO_INCREMENT = 1;</div>
                    @{
                        var sqlList = new System.Text.StringBuilder();

                        var currentId = 0;
                        Action<int?, IEnumerable<MenuInfo>> func = null;
                        func = new Action<int?, IEnumerable<MenuInfo>>((parentId , list) =>
                        {
                            var sorted = 0;
                            foreach (var menu in list)
                            {
                                if (menu.Privilege.HasValue)
                                {
                                    sqlList.AppendFormat(
                                        "<div>INSERT INTO sys_menu (ParentMenuId, PrivilegeCode, Name, Icon, Description, Sorted, IsVisible) VALUES ({0}, '{1}', '{2}', {3}, '{4}', {5}, {6});</div>",
                                        parentId.HasValue ? parentId.Value.ToString() : "NULL",
                                        menu.Privilege.Value.ToString(),
                                        menu.Name,
                                        menu.Icon.HasValue() ? "'" + menu.Icon + "'" : "NULL",
                                        menu.Description,
                                        sorted++,
                                        menu.IsVisible ? 1 : 0
                                    );
                                }
                                else
                                {
                                    sqlList.AppendFormat(
                                        "<div>INSERT INTO sys_menu (ParentMenuId, PrivilegeCode, Name, Icon, Description, Sorted, IsVisible) VALUES ({0}, NULL, '{1}', {2}, '{3}', {4}, {5});</div>",
                                        parentId.HasValue ? parentId.Value.ToString() : "NULL",
                                        menu.Name,
                                        menu.Icon.HasValue() ? "'" + menu.Icon + "'" : "NULL",
                                        menu.Description,
                                        sorted++,
                                        menu.IsVisible ? 1 : 0
                                    );
                                }
                                ++currentId;

                                if (menu.SubMenuList != null && menu.SubMenuList.Any())
                                {
                                    func(currentId, menu.SubMenuList);
                                }
                            }
                        });
                        func(null, menuList);
                        @Html.Raw(sqlList.ToString())
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Project.Template.Web/Areas/System/Views/Menu/ParentMenu.cshtml
@model Framework.Models.Menu.MenuInfo
@{ Layout = null; }

<div class="row">
    <div class="col-sm-20 col-sm-offset-2">
        @using (Html.BeginForm("ParentMenu", "Menu", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-15">
                        @Html.RequireLabelFor(m => m.Name, new { @class = "control-label" })
                        @Html.PlaceholderTextBoxFor(m => m.Name, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Name)
                    </div>
                    <div class="col-sm-9">
                        @Html.RequireLabelFor(m => m.Icon, new { @class = "control-label" })
                        @Html.PlaceholderTextBoxFor(m => m.Icon, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Icon)
                    </div>
                </div>
            </div>
            <div class="form-group">
                @Html.RequireLabelFor(m => m.Description, new { @class = "control-label" })
                @Html.PlaceholderTextBoxFor(m => m.Description, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Description)
            </div>

            <div class="form-group mt30">
                <button type="submit" class="btn btn-primary btn-block">确定</button>
            </div>
        }
    </div>
</div>

Project.Template.Web/Areas/System/Views/Menu/SubMenu.cshtml
@using Framework.Privilege;
@{ Layout = null; }

<div class="row">
    <div class="col-sm-20 col-sm-offset-2">
        @using (Html.BeginForm("SubMenu", "Menu", FormMethod.Post, new { id = "formAddSubMenu", @class = "form-horizontal" }))
        {
            var groupList = EnumExtension.GetEnumList<PrivilegeCode>()
                .Select(code =>
                {
                    var group = code.ToString().Replace("URL_", null);
                    group = group.Substring(0, group.LastIndexOf("_"));
                    return new Tuple<string, string, string, int>(group, code.ToString(), code.ToMessage(), (int)code);
                })
                .Where(code => code.Item2.StartsWith("URL_") && !code.Item3.StartsWith("POST-"))
                .OrderBy(code => code.Item1)
                .GroupBy(code => code.Item1);

            foreach (var group in groupList)
            {
                <div name="group" class="form-group">
                    <h5 class="mb5">@group.Key</h5>

                    @foreach (var privilege in group)
                    {
                        <label class="checkbox checkbox-inline checkbox-primary">
                            <input type="checkbox" value="@privilege.Item4" data-name="@privilege.Item3" />
                            <span>@privilege.Item3</span>
                        </label>
                    }
                </div>
            }

            <div id="divNullMessage" class="form-group app-hide">
                <span class="field-validation-error text-fs-sm">没有更多界面了</span>
            </div>

            <div id="divInvalidMessage" class="form-group app-hide">
                <span class="field-validation-error">请先选择菜单界面</span>
            </div>

            <div class="form-group mt30">
                @if (ViewBag.CanAddParentMenu)
                {
                    <div class="row">
                        <div class="col-sm-8">
                            <button id="btnAddParentMenu" type="button" class="btn btn-default btn-block">添加父级菜单</button>
                        </div>
                        <div class="col-sm-16">
                            <button type="submit" class="btn btn-primary btn-block">添加</button>
                        </div>
                    </div>
                }
                else
                {
                    <button type="submit" class="btn btn-primary btn-block">添加</button>
                }
            </div>
        }
    </div>
</div>

<script type="text/javascript">
    $(function () {
        $.each(MenuList, function (i, v) {
            if (v.privilege !== undefined) {
                $('#formAddSubMenu input[type="checkbox"][value="' + v.privilege + '"]').parent().remove();
            }
        });
        $('#formAddSubMenu div[name="group"]').each(function (i, v) {
            if (!$(v).find('input[type="checkbox"]').length) {
                $(v).remove();
            }
        });
        if (!$('#formAddSubMenu div[name="group"]').length) {
            $('#divNullMessage').show();
            $('button[type="submit"]').attr({ disabled: true });
        }
    });
</script>